services:
  # قاعدة بيانات PostgreSQL
  - type: psql
    name: scanner-db
    plan: free # أو أي خطة أخرى
    version: "14"
    region: frankfurt # اختر المنطقة الأقرب لك

  # تطبيق الويب (الخدمة الرئيسية)
  - type: web
    name: ethical-scanner
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn 'ethical_v5:app'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12. # استخدم نفس إصدار Python الذي تستخدمه محليًا
      - key: FLASK_APP
        value: ethical_v5.py
      - key: DATABASE_URL
        fromDatabase:
          name: scanner-db
          property: connectionString
      - key: FLASK_SECRET_KEY

        generateValue: true
